package examinationsprojekt.repositories;

import examinationsprojekt.models.*;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.List;

public class AccountListRepository implements IAccountRepository {
    private static final List<Account> accounts = new ArrayList<>();

    /* UNCOMMENT FOR TEST ACCOUNTS AND TRANSACTIONS FROM ACCOUNTLISTREPOSITORY
    private static final List<Account> accounts = readyToImportTestAccountsAndTransactions();
    */

    public boolean save(Account createdAccount) {
        return accounts.add(createdAccount);
    }

    public List<Account> findAll() {
        return new ArrayList<>(accounts);
    }

    public boolean update(Account updatedAccount) {
        for (Account account : accounts) {
            if (account.getName().equals(updatedAccount.getName())) {
                accounts.set(accounts.indexOf(account), updatedAccount);
                return true;
            }
        }
        return false;
    }

    public boolean delete(Account deletedAccount) {
        return accounts.remove(deletedAccount);
    }

    private static List<Account> readyToImportTestAccountsAndTransactions() { //kindly generated by chatGPT
        List<Account> accountsToImport = new ArrayList<>();

        //Test account 1: Alice, Checking account
        Account alice = new CheckingAccount("Private checking account", "Alice", AccountTypes.CHECKING);

        alice.addTransactionToList(new Transaction(28000.00, LocalDateTime.of(2022,1,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12000.00, LocalDateTime.of(2022,1,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-420.00, LocalDateTime.of(2022,1,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-290.00, LocalDateTime.of(2022,1,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-750.00, LocalDateTime.of(2022,1,7,17,30).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA weekly groceries", false));
        alice.addTransactionToList(new Transaction(-645.20, LocalDateTime.of(2022,1,21,18,10).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Hemköp groceries", false));
        alice.addTransactionToList(new Transaction(-140.00, LocalDateTime.of(2022,1,10,8,0).toInstant(ZoneOffset.UTC), TransactionTypes.TRANSPORT, "SL monthly card", false));
        alice.addTransactionToList(new Transaction(-95.00, LocalDateTime.of(2022,1,12,13,0).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Coffee & lunch store", false));
        alice.addTransactionToList(new Transaction(28000.00, LocalDateTime.of(2022,2,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12000.00, LocalDateTime.of(2022,2,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-450.00, LocalDateTime.of(2022,2,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-295.00, LocalDateTime.of(2022,2,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-820.00, LocalDateTime.of(2022,2,4,17,0).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Willys groceries", false));
        alice.addTransactionToList(new Transaction(-590.00, LocalDateTime.of(2022,2,18,18,30).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-160.00, LocalDateTime.of(2022,2,10,8,0).toInstant(ZoneOffset.UTC), TransactionTypes.TRANSPORT, "Taxi ride", false));
        alice.addTransactionToList(new Transaction(-129.00, LocalDateTime.of(2022,2,26,18,0).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Board game night", false));
        alice.addTransactionToList(new Transaction(28000.00, LocalDateTime.of(2022,3,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12000.00, LocalDateTime.of(2022,3,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-470.00, LocalDateTime.of(2022,3,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-300.00, LocalDateTime.of(2022,3,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-760.00, LocalDateTime.of(2022,3,4,17,20).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Matbutiken groceries", false));
        alice.addTransactionToList(new Transaction(-698.00, LocalDateTime.of(2022,3,18,17,50).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-320.00, LocalDateTime.of(2022,3,12,12,30).toInstant(ZoneOffset.UTC), TransactionTypes.TRANSPORT, "Taxi to event", false));
        alice.addTransactionToList(new Transaction(28000.00, LocalDateTime.of(2022,4,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12500.00, LocalDateTime.of(2022,4,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent (increased)", false));
        alice.addTransactionToList(new Transaction(-420.00, LocalDateTime.of(2022,4,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-295.00, LocalDateTime.of(2022,4,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-712.50, LocalDateTime.of(2022,4,7,17,30).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA weekly groceries", false));
        alice.addTransactionToList(new Transaction(-645.00, LocalDateTime.of(2022,4,21,18,10).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Hemköp groceries", false));
        alice.addTransactionToList(new Transaction(-140.00, LocalDateTime.of(2022,4,10,8,0).toInstant(ZoneOffset.UTC), TransactionTypes.TRANSPORT, "Local bus card", false));
        alice.addTransactionToList(new Transaction(28000.00, LocalDateTime.of(2022,5,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12500.00, LocalDateTime.of(2022,5,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-470.00, LocalDateTime.of(2022,5,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-300.00, LocalDateTime.of(2022,5,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-760.00, LocalDateTime.of(2022,5,4,17,20).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Matbutiken groceries", false));
        alice.addTransactionToList(new Transaction(-698.00, LocalDateTime.of(2022,5,18,17,50).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-320.00, LocalDateTime.of(2022,5,12,12,30).toInstant(ZoneOffset.UTC), TransactionTypes.TRANSPORT, "Taxi to appointment", false));
        alice.addTransactionToList(new Transaction(-899.00, LocalDateTime.of(2022,5,27,15,0).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "New jacket", false));
        alice.addTransactionToList(new Transaction(-200.00, LocalDateTime.of(2022,5,24,16,0).toInstant(ZoneOffset.UTC), TransactionTypes.DONATIONS, "Charity donation", false));
        alice.addTransactionToList(new Transaction(500.00, LocalDateTime.of(2022,5,1,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.GIFT, "Gift from friend", true));
        alice.addTransactionToList(new Transaction(28000.00, LocalDateTime.of(2022,6,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12500.00, LocalDateTime.of(2022,6,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-480.00, LocalDateTime.of(2022,6,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-310.00, LocalDateTime.of(2022,6,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-745.00, LocalDateTime.of(2022,6,5,17,15).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-630.00, LocalDateTime.of(2022,6,18,18,10).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Willys groceries", false));
        alice.addTransactionToList(new Transaction(-150.00, LocalDateTime.of(2022,6,10,8,0).toInstant(ZoneOffset.UTC), TransactionTypes.TRANSPORT, "Bus card", false));
        alice.addTransactionToList(new Transaction(-1200.00, LocalDateTime.of(2022,6,22,12,0).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Midsummer weekend trip", false));
        alice.addTransactionToList(new Transaction(28000.00, LocalDateTime.of(2022,7,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12500.00, LocalDateTime.of(2022,7,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-480.00, LocalDateTime.of(2022,7,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-310.00, LocalDateTime.of(2022,7,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-850.00, LocalDateTime.of(2022,7,5,17,20).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-5100.00, LocalDateTime.of(2022,7,10,9,30).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Vacation to Gotland", false));
        alice.addTransactionToList(new Transaction(28000.00, LocalDateTime.of(2022,8,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12500.00, LocalDateTime.of(2022,8,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-470.00, LocalDateTime.of(2022,8,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-305.00, LocalDateTime.of(2022,8,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(7-90.00, LocalDateTime.of(2022,8,8,18,0).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Willys groceries", false));
        alice.addTransactionToList(new Transaction(4-20.00, LocalDateTime.of(2022,8,14,12,30).toInstant(ZoneOffset.UTC), TransactionTypes.HEALTH, "Dentist checkup", false));
        alice.addTransactionToList(new Transaction(28000.00, LocalDateTime.of(2022,9,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12500.00, LocalDateTime.of(2022,9,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-475.00, LocalDateTime.of(2022,9,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-310.00, LocalDateTime.of(2022,9,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-720.00, LocalDateTime.of(2022,9,5,17,30).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-1900.00, LocalDateTime.of(2022,9,12,10,30).toInstant(ZoneOffset.UTC), TransactionTypes.EDUCATION, "Online Swedish course", false));
        alice.addTransactionToList(new Transaction(28000.00, LocalDateTime.of(2022,10,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12500.00, LocalDateTime.of(2022,10,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-480.00, LocalDateTime.of(2022,10,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-310.00, LocalDateTime.of(2022,10,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-740.00, LocalDateTime.of(2022,10,6,17,10).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Hemköp groceries", false));
        alice.addTransactionToList(new Transaction(-2600.00, LocalDateTime.of(2022,10,10,13,0).toInstant(ZoneOffset.UTC), TransactionTypes.HEALTH, "Optician visit + glasses", false));
        alice.addTransactionToList(new Transaction(28000.00, LocalDateTime.of(2022,11,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12500.00, LocalDateTime.of(2022,11,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-470.00, LocalDateTime.of(2022,11,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-310.00, LocalDateTime.of(2022,11,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-715.00, LocalDateTime.of(2022,11,7,17,40).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Willys groceries", false));
        alice.addTransactionToList(new Transaction(-450.00, LocalDateTime.of(2022,11,26,12,30).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "Winter boots", false));
        alice.addTransactionToList(new Transaction(28000.00, LocalDateTime.of(2022,12,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12500.00, LocalDateTime.of(2022,12,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-490.00, LocalDateTime.of(2022,12,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-310.00, LocalDateTime.of(2022,12,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-740.00, LocalDateTime.of(2022,12,5,17,20).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(2000.00, LocalDateTime.of(2022,12,23,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.GIFT, "Christmas bonus", true));alice.addTransactionToList(new Transaction(3500.00, LocalDateTime.of(2022,12,24,15,30).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "Christmas gifts", false));
        alice.addTransactionToList(new Transaction(29000.00, LocalDateTime.of(2023,1,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary (raise)", true));
        alice.addTransactionToList(new Transaction(-12600.00, LocalDateTime.of(2023,1,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-495.00, LocalDateTime.of(2023,1,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-315.00, LocalDateTime.of(2023,1,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-770.00, LocalDateTime.of(2023,1,5,17,20).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Willys groceries", false));
        alice.addTransactionToList(new Transaction(-550.00, LocalDateTime.of(2023,1,22,19,0).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Cinema with friends", false));
        alice.addTransactionToList(new Transaction(29000.00, LocalDateTime.of(2023,2,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12600.00, LocalDateTime.of(2023,2,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-510.00, LocalDateTime.of(2023,2,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-315.00, LocalDateTime.of(2023,2,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-820.00, LocalDateTime.of(2023,2,10,17,30).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-1900.00, LocalDateTime.of(2023,2,14,13,0).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "Winter jacket & boots", false));alice.addTransactionToList(new Transaction(29000.00, LocalDateTime.of(2023,3,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12600.00, LocalDateTime.of(2023,3,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-520.00, LocalDateTime.of(2023,3,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-315.00, LocalDateTime.of(2023,3,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-730.00, LocalDateTime.of(2023,3,4,17,30).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Willys groceries", false));
        alice.addTransactionToList(new Transaction(-450.00, LocalDateTime.of(2023,3,12,11,30).toInstant(ZoneOffset.UTC), TransactionTypes.HEALTH, "Dentist checkup", false));
        alice.addTransactionToList(new Transaction(29000.00, LocalDateTime.of(2023,4,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12600.00, LocalDateTime.of(2023,4,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-520.00, LocalDateTime.of(2023,4,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-315.00, LocalDateTime.of(2023,4,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-750.00, LocalDateTime.of(2023,4,6,17,0).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-2800.00, LocalDateTime.of(2023,4,17,13,30).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Spring concert in Stockholm", false));
        alice.addTransactionToList(new Transaction(29000.00, LocalDateTime.of(2023,5,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12600.00, LocalDateTime.of(2023,5,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-510.00, LocalDateTime.of(2023,5,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-315.00, LocalDateTime.of(2023,5,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-830.00, LocalDateTime.of(2023,5,5,18,10).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Willys groceries", false));
        alice.addTransactionToList(new Transaction(-4500.00, LocalDateTime.of(2023,5,21,14,0).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Weekend in Copenhagen", false));
        alice.addTransactionToList(new Transaction(29000.00, LocalDateTime.of(2023,6,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12600.00, LocalDateTime.of(2023,6,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-520.00, LocalDateTime.of(2023,6,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-320.00, LocalDateTime.of(2023,6,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-710.00, LocalDateTime.of(2023,6,9,18,0).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-2200.00, LocalDateTime.of(2023,6,23,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Midsummer trip to the coast", false));
        alice.addTransactionToList(new Transaction(29000.00, LocalDateTime.of(2023,7,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12600.00, LocalDateTime.of(2023,7,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-510.00, LocalDateTime.of(2023,7,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-320.00, LocalDateTime.of(2023,7,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-760.00, LocalDateTime.of(2023,7,4,17,30).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Willys groceries", false));
        alice.addTransactionToList(new Transaction(-6900.00, LocalDateTime.of(2023,7,16,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Summer vacation in Spain", false));
        alice.addTransactionToList(new Transaction(29000.00, LocalDateTime.of(2023,8,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12600.00, LocalDateTime.of(2023,8,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-520.00, LocalDateTime.of(2023,8,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-320.00, LocalDateTime.of(2023,8,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-740.00, LocalDateTime.of(2023,8,6,18,0).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-390.00, LocalDateTime.of(2023,8,18,13,30).toInstant(ZoneOffset.UTC), TransactionTypes.HEALTH, "Pharmacy purchase", false));
        alice.addTransactionToList(new Transaction(29000.00, LocalDateTime.of(2023,9,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12600.00, LocalDateTime.of(2023,9,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-515.00, LocalDateTime.of(2023,9,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-320.00, LocalDateTime.of(2023,9,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-780.00, LocalDateTime.of(2023,9,8,18,0).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Willys groceries", false));
        alice.addTransactionToList(new Transaction(-2100.00, LocalDateTime.of(2023,9,25,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.EDUCATION, "Online UX design course", false));
        alice.addTransactionToList(new Transaction(-29000.00, LocalDateTime.of(2023,10,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12600.00, LocalDateTime.of(2023,10,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-510.00, LocalDateTime.of(2023,10,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-320.00, LocalDateTime.of(2023,10,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-740.00, LocalDateTime.of(2023,10,6,17,10).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-1800.00, LocalDateTime.of(2023,10,14,12,0).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "Autumn clothes", false));
        alice.addTransactionToList(new Transaction(29000.00, LocalDateTime.of(2023,11,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12600.00, LocalDateTime.of(2023,11,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-515.00, LocalDateTime.of(2023,11,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-320.00, LocalDateTime.of(2023,11,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-760.00, LocalDateTime.of(2023,11,5,18,0).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Willys groceries", false));
        alice.addTransactionToList(new Transaction(-3100.00, LocalDateTime.of(2023,11,26,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "New smartphone", false));
        alice.addTransactionToList(new Transaction(29000.00, LocalDateTime.of(2023,12,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12600.00, LocalDateTime.of(2023,12,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-530.00, LocalDateTime.of(2023,12,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-320.00, LocalDateTime.of(2023,12,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-780.00, LocalDateTime.of(2023,12,7,17,10).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(2300.00, LocalDateTime.of(2023,12,22,12,0).toInstant(ZoneOffset.UTC), TransactionTypes.GIFT, "Christmas bonus", true));
        alice.addTransactionToList(new Transaction(-3700.00, LocalDateTime.of(2023,12,23,15,30).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "Christmas gifts", false));
        alice.addTransactionToList(new Transaction(30000.00, LocalDateTime.of(2024,1,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12900.00, LocalDateTime.of(2024,1,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-550.00, LocalDateTime.of(2024,1,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-330.00, LocalDateTime.of(2024,1,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-790.00, LocalDateTime.of(2024,1,6,18,0).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Willys groceries", false));
        alice.addTransactionToList(new Transaction(-2200.00, LocalDateTime.of(2024,1,19,13,0).toInstant(ZoneOffset.UTC), TransactionTypes.HEALTH, "New gym membership", false));
        alice.addTransactionToList(new Transaction(30000.00, LocalDateTime.of(2024,2,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12900.00, LocalDateTime.of(2024,2,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-550.00, LocalDateTime.of(2024,2,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-330.00, LocalDateTime.of(2024,2,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-760.00, LocalDateTime.of(2024,2,9,17,20).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-3400.00, LocalDateTime.of(2024,2,18,14,0).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Ski trip to Sälen", false));
        alice.addTransactionToList(new Transaction(30000.00, LocalDateTime.of(2024,3,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12900.00, LocalDateTime.of(2024,3,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-545.00, LocalDateTime.of(2024,3,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-330.00, LocalDateTime.of(2024,3,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-750.00, LocalDateTime.of(2024,3,8,18,0).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Willys groceries", false));
        alice.addTransactionToList(new Transaction(-2500.00, LocalDateTime.of(2024,3,22,13,0).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "Spring clothing update", false));
        alice.addTransactionToList(new Transaction(30000.00, LocalDateTime.of(2024,4,25,14,30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary", true));
        alice.addTransactionToList(new Transaction(-12900.00, LocalDateTime.of(2024,4,1,9,0).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "Monthly rent", false));
        alice.addTransactionToList(new Transaction(-550.00, LocalDateTime.of(2024,4,15,10,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-330.00, LocalDateTime.of(2024,4,20,11,0).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Internet bill", false));
        alice.addTransactionToList(new Transaction(-720.00, LocalDateTime.of(2024,4,5,17,0).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "ICA groceries", false));
        alice.addTransactionToList(new Transaction(-4100.00, LocalDateTime.of(2024,4,17,13,30).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Easter trip to Berlin", false));
        alice.addTransactionToList(new Transaction(15200.0, LocalDateTime.of(2024, 8, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-680.0, LocalDateTime.of(2024, 8, 26, 12, 45).toInstant(ZoneOffset.UTC), TransactionTypes.EDUCATION, "Online design course fee", false));
        alice.addTransactionToList(new Transaction(-125.0, LocalDateTime.of(2024, 8, 27, 8, 10).toInstant(ZoneOffset.UTC), TransactionTypes.TRANSPORT, "SL commuter pass top-up", false));
        alice.addTransactionToList(new Transaction(-1100.0, LocalDateTime.of(2024, 8, 30, 18, 20).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "H&M end-of-summer clothes", false));
        alice.addTransactionToList(new Transaction(-55.0, LocalDateTime.of(2024, 8, 31, 10, 15).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Fika at Espresso House", false));
        alice.addTransactionToList(new Transaction(15300.0, LocalDateTime.of(2024, 9, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-7200.0, LocalDateTime.of(2024, 9, 26, 17, 00).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "September rent", false));
        alice.addTransactionToList(new Transaction(-900.0, LocalDateTime.of(2024, 9, 27, 11, 30).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity and internet bill", false));
        alice.addTransactionToList(new Transaction(-3400.0, LocalDateTime.of(2024, 9, 29, 15, 10).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Automatic monthly transfer to savings", false));
        alice.addTransactionToList(new Transaction(-250.0, LocalDateTime.of(2024, 9, 30, 14, 55).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Cinema date", false));
        alice.addTransactionToList(new Transaction(15400.0, LocalDateTime.of(2024, 10, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-780.0, LocalDateTime.of(2024, 10, 26, 12, 50).toInstant(ZoneOffset.UTC), TransactionTypes.HEALTH, "Dental cleaning", false));
        alice.addTransactionToList(new Transaction(-90.0, LocalDateTime.of(2024, 10, 27, 8, 10).toInstant(ZoneOffset.UTC), TransactionTypes.TRANSPORT, "Bus ticket", false));
        alice.addTransactionToList(new Transaction(-1300.0, LocalDateTime.of(2024, 10, 30, 18, 40).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "Autumn wardrobe refresh", false));
        alice.addTransactionToList(new Transaction(-480.0, LocalDateTime.of(2024, 10, 31, 10, 15).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Concert ticket", false));
        alice.addTransactionToList(new Transaction(15600.0, LocalDateTime.of(2024, 11, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-7100.0, LocalDateTime.of(2024, 11, 26, 17, 00).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "November rent", false));
        alice.addTransactionToList(new Transaction(-950.0, LocalDateTime.of(2024, 11, 27, 11, 15).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity and water bill", false));
        alice.addTransactionToList(new Transaction(-3700.0, LocalDateTime.of(2024, 11, 29, 15, 10).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Monthly savings deposit", false));
        alice.addTransactionToList(new Transaction(-1750.0, LocalDateTime.of(2024, 11, 30, 19, 20).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "Black Friday deals", false));
        alice.addTransactionToList(new Transaction(15800.0, LocalDateTime.of(2024, 12, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(5000.0, LocalDateTime.of(2024, 12, 26, 10, 45).toInstant(ZoneOffset.UTC), TransactionTypes.GIFT, "Christmas bonus", true));
        alice.addTransactionToList(new Transaction(-620.0, LocalDateTime.of(2024, 12, 27, 8, 15).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Christmas dinner ingredients", false));
        alice.addTransactionToList(new Transaction(-4500.0, LocalDateTime.of(2024, 12, 28, 19, 00).toInstant(ZoneOffset.UTC), TransactionTypes.DONATIONS, "Holiday charity donation", false));
        alice.addTransactionToList(new Transaction(-3000.0, LocalDateTime.of(2024, 12, 30, 17, 40).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "End-of-year savings", false));
        alice.addTransactionToList(new Transaction(16000.0, LocalDateTime.of(2025, 1, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-6900.0, LocalDateTime.of(2025, 1, 26, 17, 00).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "January rent", false));
        alice.addTransactionToList(new Transaction(-950.0, LocalDateTime.of(2025, 1, 27, 11, 30).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Heating and electricity bill", false));
        alice.addTransactionToList(new Transaction(-1200.0, LocalDateTime.of(2025, 1, 28, 15, 10).toInstant(ZoneOffset.UTC), TransactionTypes.HEALTH, "New gym membership", false));
        alice.addTransactionToList(new Transaction(-250.0, LocalDateTime.of(2025, 1, 30, 14, 55).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Netflix and Spotify", false));
        alice.addTransactionToList(new Transaction(16200.0, LocalDateTime.of(2025, 2, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-7200.0, LocalDateTime.of(2025, 2, 26, 17, 00).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "February rent", false));
        alice.addTransactionToList(new Transaction(-900.0, LocalDateTime.of(2025, 2, 27, 11, 15).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity and water bill", false));
        alice.addTransactionToList(new Transaction(-300.0, LocalDateTime.of(2025, 2, 28, 12, 30).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Lunch with coworkers", false));
        alice.addTransactionToList(new Transaction(-3600.0, LocalDateTime.of(2025, 2, 28, 19, 00).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Automatic savings transfer", false));
        alice.addTransactionToList(new Transaction(16300.0, LocalDateTime.of(2025, 3, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-850.0, LocalDateTime.of(2025, 3, 26, 10, 45).toInstant(ZoneOffset.UTC), TransactionTypes.HEALTH, "Doctor appointment", false));
        alice.addTransactionToList(new Transaction(-100.0, LocalDateTime.of(2025, 3, 27, 8, 15).toInstant(ZoneOffset.UTC), TransactionTypes.TRANSPORT, "Commuter card refill", false));
        alice.addTransactionToList(new Transaction(-1500.0, LocalDateTime.of(2025, 3, 28, 18, 20).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "New spring clothes", false));
        alice.addTransactionToList(new Transaction(-520.0, LocalDateTime.of(2025, 3, 30, 10, 30).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Weekend outing", false));
        alice.addTransactionToList(new Transaction(16500.0, LocalDateTime.of(2025, 4, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-7000.0, LocalDateTime.of(2025, 4, 26, 17, 00).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "April rent", false));
        alice.addTransactionToList(new Transaction(-880.0, LocalDateTime.of(2025, 4, 27, 11, 15).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-1800.0, LocalDateTime.of(2025, 4, 28, 15, 10).toInstant(ZoneOffset.UTC), TransactionTypes.EDUCATION, "New design course", false));
        alice.addTransactionToList(new Transaction(-4000.0, LocalDateTime.of(2025, 4, 29, 19, 00).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Monthly savings", false));
        alice.addTransactionToList(new Transaction(16600.0, LocalDateTime.of(2025, 5, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-600.0, LocalDateTime.of(2025, 5, 26, 10, 45).toInstant(ZoneOffset.UTC), TransactionTypes.HEALTH, "Optician visit", false));
        alice.addTransactionToList(new Transaction(-240.0, LocalDateTime.of(2025, 5, 27, 8, 15).toInstant(ZoneOffset.UTC), TransactionTypes.FOOD, "Groceries for the week", false));
        alice.addTransactionToList(new Transaction(-1700.0, LocalDateTime.of(2025, 5, 28, 18, 20).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Summer music festival", false));
        alice.addTransactionToList(new Transaction(-3800.0, LocalDateTime.of(2025, 5, 30, 19, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Monthly savings transfer", false));
        alice.addTransactionToList(new Transaction(16700.0, LocalDateTime.of(2025, 6, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-7200.0, LocalDateTime.of(2025, 6, 26, 17, 00).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "June rent", false));
        alice.addTransactionToList(new Transaction(-950.0, LocalDateTime.of(2025, 6, 27, 11, 20).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity and broadband", false));
        alice.addTransactionToList(new Transaction(-2100.0, LocalDateTime.of(2025, 6, 28, 15, 40).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Midsummer weekend trip to Gotland", false));
        alice.addTransactionToList(new Transaction(-4200.0, LocalDateTime.of(2025, 6, 30, 18, 15).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Monthly savings transfer", false));
        alice.addTransactionToList(new Transaction(16800.0, LocalDateTime.of(2025, 7, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-7400.0, LocalDateTime.of(2025, 7, 26, 17, 00).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "July rent", false));
        alice.addTransactionToList(new Transaction(-800.0, LocalDateTime.of(2025, 7, 27, 11, 15).toInstant(ZoneOffset.UTC), TransactionTypes.HEALTH, "Massage therapy session", false));
        alice.addTransactionToList(new Transaction(-3500.0, LocalDateTime.of(2025, 7, 29, 14, 30).toInstant(ZoneOffset.UTC), TransactionTypes.ENTERTAINMENT, "Summer holiday in Copenhagen", false));
        alice.addTransactionToList(new Transaction(-3900.0, LocalDateTime.of(2025, 7, 30, 19, 00).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Automatic savings", false));
        alice.addTransactionToList(new Transaction(16900.0, LocalDateTime.of(2025, 8, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-7200.0, LocalDateTime.of(2025, 8, 26, 17, 00).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "August rent", false));
        alice.addTransactionToList(new Transaction(-980.0, LocalDateTime.of(2025, 8, 27, 11, 10).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity and internet", false));
        alice.addTransactionToList(new Transaction(-1500.0, LocalDateTime.of(2025, 8, 28, 16, 00).toInstant(ZoneOffset.UTC), TransactionTypes.EDUCATION, "New language course in Spanish", false));
        alice.addTransactionToList(new Transaction(-4100.0, LocalDateTime.of(2025, 8, 30, 19, 00).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "End-of-summer savings", false));
        alice.addTransactionToList(new Transaction(17000.0, LocalDateTime.of(2025, 9, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-7300.0, LocalDateTime.of(2025, 9, 26, 17, 00).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "September rent", false));
        alice.addTransactionToList(new Transaction(-900.0, LocalDateTime.of(2025, 9, 27, 11, 00).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity bill", false));
        alice.addTransactionToList(new Transaction(-2200.0, LocalDateTime.of(2025, 9, 28, 18, 20).toInstant(ZoneOffset.UTC), TransactionTypes.SHOPPING, "New autumn coat and boots", false));
        alice.addTransactionToList(new Transaction(-4000.0, LocalDateTime.of(2025, 9, 30, 19, 10).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Monthly savings transfer", false));
        alice.addTransactionToList(new Transaction(17100.0, LocalDateTime.of(2025, 10, 25, 9, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SALARY, "Monthly salary from IKEA", true));
        alice.addTransactionToList(new Transaction(-7500.0, LocalDateTime.of(2025, 10, 26, 17, 00).toInstant(ZoneOffset.UTC), TransactionTypes.HOUSING, "October rent", false));
        alice.addTransactionToList(new Transaction(-980.0, LocalDateTime.of(2025, 10, 27, 11, 15).toInstant(ZoneOffset.UTC), TransactionTypes.UTILITIES, "Electricity and water bill", false));
        alice.addTransactionToList(new Transaction(-1300.0, LocalDateTime.of(2025, 10, 28, 18, 45).toInstant(ZoneOffset.UTC), TransactionTypes.HEALTH, "Flu vaccine and check-up", false));
        alice.addTransactionToList(new Transaction(-4200.0, LocalDateTime.of(2025, 10, 30, 19, 30).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Automatic monthly savings", false));

        for (Transaction transaction : alice.getTransactionsCopy()) {
            alice.setBalance(transaction.getAmount());
        }

        accountsToImport.add(alice);

        //Test account 2: Björn, Savings account
        Account bjorn = new SavingsAccount("Savings account", "Bjorn", AccountTypes.CHECKING, 0.02);

        bjorn.addTransactionToList(new Transaction(2000.0, LocalDateTime.of(2022, 1, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Monthly transfer to savings", true));
        bjorn.addTransactionToList(new Transaction(10.0, LocalDateTime.of(2022, 3, 31, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(2500.0, LocalDateTime.of(2022, 4, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Monthly transfer to savings", true));
        bjorn.addTransactionToList(new Transaction(12.0, LocalDateTime.of(2022, 6, 30, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(2200.0, LocalDateTime.of(2022, 7, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Monthly transfer to savings", true));
        bjorn.addTransactionToList(new Transaction(2500.0, LocalDateTime.of(2022, 9, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Monthly transfer to savings", true));
        bjorn.addTransactionToList(new Transaction(15.0, LocalDateTime.of(2022, 9, 30, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(-1000.0, LocalDateTime.of(2022, 12, 10, 15, 20).toInstant(ZoneOffset.UTC), TransactionTypes.OTHER_SPENDING, "Christmas gifts", false));
        bjorn.addTransactionToList(new Transaction(18.0, LocalDateTime.of(2022, 12, 31, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(2500.0, LocalDateTime.of(2023, 1, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "New year savings transfer", true));
        bjorn.addTransactionToList(new Transaction(20.0, LocalDateTime.of(2023, 3, 31, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(3000.0, LocalDateTime.of(2023, 4, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Monthly transfer to savings", true));
        bjorn.addTransactionToList(new Transaction(25.0, LocalDateTime.of(2023, 6, 30, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(3500.0, LocalDateTime.of(2023, 7, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Summer savings deposit", true));
        bjorn.addTransactionToList(new Transaction(28.0, LocalDateTime.of(2023, 9, 30, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(-1500.0, LocalDateTime.of(2023, 11, 15, 14, 10).toInstant(ZoneOffset.UTC), TransactionTypes.OTHER_SPENDING, "Home improvement purchase", false));
        bjorn.addTransactionToList(new Transaction(32.0, LocalDateTime.of(2023, 12, 31, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(3000.0, LocalDateTime.of(2024, 1, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Monthly transfer to savings", true));
        bjorn.addTransactionToList(new Transaction(35.0, LocalDateTime.of(2024, 3, 31, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(3500.0, LocalDateTime.of(2024, 4, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Spring savings", true));
        bjorn.addTransactionToList(new Transaction(38.0, LocalDateTime.of(2024, 6, 30, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(3200.0, LocalDateTime.of(2024, 7, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Summer savings", true));
        bjorn.addTransactionToList(new Transaction(40.0, LocalDateTime.of(2024, 9, 30, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(-20000.0, LocalDateTime.of(2024, 10, 15, 14, 10).toInstant(ZoneOffset.UTC), TransactionTypes.OTHER_SPENDING, "Used car down payment", false));
        bjorn.addTransactionToList(new Transaction(42.0, LocalDateTime.of(2024, 12, 31, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(3000.0, LocalDateTime.of(2025, 1, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "New year savings", true));
        bjorn.addTransactionToList(new Transaction(45.0, LocalDateTime.of(2025, 3, 31, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(3500.0, LocalDateTime.of(2025, 4, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Monthly transfer to savings", true));
        bjorn.addTransactionToList(new Transaction(50.0, LocalDateTime.of(2025, 6, 30, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(3000.0, LocalDateTime.of(2025, 7, 5, 9, 45).toInstant(ZoneOffset.UTC), TransactionTypes.SAVINGS, "Summer savings deposit", true));
        bjorn.addTransactionToList(new Transaction(52.0, LocalDateTime.of(2025, 9, 30, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));
        bjorn.addTransactionToList(new Transaction(-5000.0, LocalDateTime.of(2025, 10, 20, 15, 15).toInstant(ZoneOffset.UTC), TransactionTypes.OTHER_SPENDING, "Vacation withdrawal", false));
        bjorn.addTransactionToList(new Transaction(55.0, LocalDateTime.of(2025, 10, 30, 10, 0).toInstant(ZoneOffset.UTC), TransactionTypes.INTEREST, "Quarterly interest", true));

        for (Transaction transaction : bjorn.getTransactionsCopy()) {
            bjorn.setBalance(transaction.getAmount());
        }

        accountsToImport.add(bjorn);

        return accountsToImport;
    }
}
